services:
  todo_client:
    build:
      context: ./Todo_Client
      dockerfile: DockerFile
    container_name: todo_client
    environment:
      VITE_BACKEND: http://localhost:8000
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "5173:5173"
    volumes:
      - ./Todo_Client:/app
      - /app/node_modules
    depends_on:
      - todo_server
    networks:
      - appnet
    command: npm run dev -- --host 0.0.0.0 --port 5173

  todo_server:
    build: ./Todo_Server
    container_name: todo_server
    environment:
      MONGO_URL: mongodb://db:27017/todoapp
      JWT_SECRET: supersecretkey
      PORT: 8000
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:5174
      NODE_ENV: development
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - appnet
    command: node src/server.js

  db:
    image: mongo:5
    container_name: todo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
